version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release

init:
  - set PATH=C:\Qt\5.11.1\msvc2017_64;%PATH%

install:
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" .. -DIVW_MODULE_VECTORFIELDVISUALIZATION=OFF -DIVW_MODULE_VECTORFIELDVISUALIZATIONGL=OFF -DCMAKE_BUILD_TYPE=Release -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF
    - cmake -G "Visual Studio 15 2017 Win64" .. -DIVW_MODULE_VECTORFIELDVISUALIZATION=OFF -DIVW_MODULE_VECTORFIELDVISUALIZATIONGL=OFF -DCMAKE_BUILD_TYPE=Release -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\PACKAGE.vcxproj

artifacts:
  - path: build\*.exe
    name: Inviwo

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: VuweHWHk/EiUGGXnRmahl1KSF8EzGKsWDsdk1TD7OPvTmXSsv+z1d6JRIIQqVmjk
  artifact: Inviwo
  draft: false                     # tell AppVeyor to create a “draft” release so you can perform any final checks before making it public.
  force_update: true               # true to overwrite files in an existing release; default is false which will fail deployment if the release already exists on GitHub.
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
