language: cpp
sudo: false

notifications:
  email: false

matrix:
  include:
  - env: COMPILER=clang++ BUILD_TYPE=Release BUILD_TARGET=inviwo
    os: osx
    osx_image: xcode9.2
    compiler: clang

before_install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
  - export CXX=${COMPILER}
  - "${CXX} --version"
  - JOBS=2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"
  - CMAKE_VERSION=3.11.4
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt && export PATH="/usr/local/opt/qt/bin:$PATH"'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install python3'

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - cmake --build . --target ${BUILD_TARGET} -- -j${JOBS}

before_deploy:
  - cd $TRAVIS_BUILD_DIR/build
  - mkdir inviwo-macos-high-sierra
  - cp -r bin/inviwo.app inviwo-macos-high-sierra
  - zip -r inviwo-macos-high-sierra.zip inviwo-macos-high-sierra

deploy:
  provider: releases
  api_key:
    secure: HWgj/X81zqS9K5sIAzCZ4c7E3uUUqYdKMfPQY7IcvXrI4IuZ1hrybfE6TZCze5Ogy5OCkFDBMmbLZMiCYWJ74MN9brTuXc4PCbJULqr19MgdvGBDLOBI3q8BLFW43evPgW9++zshBlcgOVZkrI4qxdY2MbwnChEVd70r6Ai+0L8ityGjHenEZ2DmbFhkrnCPXSHMqUVFJqZuPdnGkb4AqL7MQ8fWfcoC2nrb0SR99mVaqN9Xj7hdXlqAfHqM0BjIy08saXVo40ZRqq4p+q0pUIoG7e0ttL/0CIdt+oG8YwQxdy4ETwQ8udRdkyNhA/X1GKkIc4T5d2Off7jbQxkawPHiwa6poxV0hhgU97BPT3rHiEnCSqLJCZSZ4/ScS78DJ0hkdte2Qg8Pa04+plAB81n6IWNviF1gdEU89LdC9xdJIUO2+J1qGlgAIT9Me+S4wCx6Hb/tbObrt1nD6YJn5qymP8EwpGNc12InM2xBYhcT9tAKSsebqz2XZSZkx5NHKTqzNu0wpQOimaQfw/EvddK73xZvIMbmFOerpSVNzw4BQHAFgeDsoPhea7/He6i5OZBo+DZmo3KiWKaRBZqbFy/7tk8KNwRf6Jj/gZtxJLU3w2gml+Rd4nqwCuxHZrIbCaIUDFgAVn8TtCn+01w3G5beMGtgMMO/rf6MZg/Rufs=
  file: $TRAVIS_BUILD_DIR/build/inviwo-macos-high-sierra.zip
  skip_cleanup: true
  on:
    repo: onc/inviwo
    tags: true
    condition: '"$TRAVIS_OS_NAME" == osx'
