language: cpp
sudo: false

notifications:
  email: false

matrix:
  include:
  - env: BUILD_TYPE=Release BUILD_TARGET=package JOBS=2
    os: osx
    osx_image: xcode10

before_install:
  - brew update
  - brew upgrade

install:
  - brew install cmake || brew upgrade cmake
  - cmake --version
  - brew install qt
  - export PATH="/usr/local/opt/qt/bin:$PATH"

before_script:
  - find /usr/local/opt/python3/Frameworks/Python.framework/Versions -iname '*.app' | xargs rm -rf
  - cd "${TRAVIS_BUILD_DIR}"
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF

script:
  - cmake --build . --target ${BUILD_TARGET} -- -j${JOBS}

before_deploy:
  - export DMG_FILE_NAME=$(find $TRAVIS_BUILD_DIR/build -maxdepth 1 -iname 'Inviwo*.dmg')

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HWgj/X81zqS9K5sIAzCZ4c7E3uUUqYdKMfPQY7IcvXrI4IuZ1hrybfE6TZCze5Ogy5OCkFDBMmbLZMiCYWJ74MN9brTuXc4PCbJULqr19MgdvGBDLOBI3q8BLFW43evPgW9++zshBlcgOVZkrI4qxdY2MbwnChEVd70r6Ai+0L8ityGjHenEZ2DmbFhkrnCPXSHMqUVFJqZuPdnGkb4AqL7MQ8fWfcoC2nrb0SR99mVaqN9Xj7hdXlqAfHqM0BjIy08saXVo40ZRqq4p+q0pUIoG7e0ttL/0CIdt+oG8YwQxdy4ETwQ8udRdkyNhA/X1GKkIc4T5d2Off7jbQxkawPHiwa6poxV0hhgU97BPT3rHiEnCSqLJCZSZ4/ScS78DJ0hkdte2Qg8Pa04+plAB81n6IWNviF1gdEU89LdC9xdJIUO2+J1qGlgAIT9Me+S4wCx6Hb/tbObrt1nD6YJn5qymP8EwpGNc12InM2xBYhcT9tAKSsebqz2XZSZkx5NHKTqzNu0wpQOimaQfw/EvddK73xZvIMbmFOerpSVNzw4BQHAFgeDsoPhea7/He6i5OZBo+DZmo3KiWKaRBZqbFy/7tk8KNwRf6Jj/gZtxJLU3w2gml+Rd4nqwCuxHZrIbCaIUDFgAVn8TtCn+01w3G5beMGtgMMO/rf6MZg/Rufs=
  file: "${DMG_FILE_NAME}"
  on:
    repo: onc/inviwo
    tags: true
    condition: '"$TRAVIS_OS_NAME" == osx'
