language: cpp
sudo: false
notifications:
  email: false

matrix:
  include:
    # XCode 9.4
    - env: COMPILER=clang++
      os: osx
      osx_image: xcode9.4
      compiler: clang

before_install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
  # Set the ${CXX} variable properly
  - export CXX=${COMPILER}
  - ${CXX} --version

  # Travis machines have 2 cores
  - JOBS=2

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - CMAKE_VERSION=3.11.4
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

  ############################################################################
  # Install Qt
  ############################################################################
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt && export PATH="/usr/local/opt/qt/bin:$PATH"'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install hdf5 --with-cxx --c++11'

before_script:
  # have CMake to generate build files
  - cd "${TRAVIS_BUILD_DIR}"
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - cmake --build . -- -j${JOBS}
