version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release

install:
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" .. -DIVW_MODULE_VECTORFIELDVISUALIZATION=OFF -DIVW_MODULE_VECTORFIELDVISUALIZATIONGL=OFF -DCMAKE_BUILD_TYPE=Release -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF
    - cmake -G "Visual Studio 15 2017 Win64" .. -DIVW_MODULE_VECTORFIELDVISUALIZATION=OFF -DIVW_MODULE_VECTORFIELDVISUALIZATIONGL=OFF -DCMAKE_BUILD_TYPE=Release -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\build\PACKAGE.vcxproj
