version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release

init:
  - set PATH=C:\Qt\5.11.1\msvc2017_64;%PATH%

install:
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" .. -DIVW_MODULE_VECTORFIELDVISUALIZATION=OFF -DIVW_MODULE_VECTORFIELDVISUALIZATIONGL=OFF -DCMAKE_BUILD_TYPE=Release -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF
    - cmake -G "Visual Studio 15 2017 Win64" .. -DIVW_MODULE_VECTORFIELDVISUALIZATION=OFF -DIVW_MODULE_VECTORFIELDVISUALIZATIONGL=OFF -DCMAKE_BUILD_TYPE=Release -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\build\PACKAGE.vcxproj

deploy:
  release: inviwo-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: HWgj/X81zqS9K5sIAzCZ4c7E3uUUqYdKMfPQY7IcvXrI4IuZ1hrybfE6TZCze5Ogy5OCkFDBMmbLZMiCYWJ74MN9brTuXc4PCbJULqr19MgdvGBDLOBI3q8BLFW43evPgW9++zshBlcgOVZkrI4qxdY2MbwnChEVd70r6Ai+0L8ityGjHenEZ2DmbFhkrnCPXSHMqUVFJqZuPdnGkb4AqL7MQ8fWfcoC2nrb0SR99mVaqN9Xj7hdXlqAfHqM0BjIy08saXVo40ZRqq4p+q0pUIoG7e0ttL/0CIdt+oG8YwQxdy4ETwQ8udRdkyNhA/X1GKkIc4T5d2Off7jbQxkawPHiwa6poxV0hhgU97BPT3rHiEnCSqLJCZSZ4/ScS78DJ0hkdte2Qg8Pa04+plAB81n6IWNviF1gdEU89LdC9xdJIUO2+J1qGlgAIT9Me+S4wCx6Hb/tbObrt1nD6YJn5qymP8EwpGNc12InM2xBYhcT9tAKSsebqz2XZSZkx5NHKTqzNu0wpQOimaQfw/EvddK73xZvIMbmFOerpSVNzw4BQHAFgeDsoPhea7/He6i5OZBo+DZmo3KiWKaRBZqbFy/7tk8KNwRf6Jj/gZtxJLU3w2gml+Rd4nqwCuxHZrIbCaIUDFgAVn8TtCn+01w3G5beMGtgMMO/rf6MZg/Rufs=
  artifact: $(APPVEYOR_BUILD_FOLDER)\build\Inviwo-v0.9.9.1.exe
  draft: false                     # tell AppVeyor to create a “draft” release so you can perform any final checks before making it public.
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
